apiVersion: kro.run/v1alpha1
kind: WebApplication
metadata:
  name: carts
  namespace: carts
spec:
  # Basic types
  appName: carts
  replicas: 1
  image: "public.ecr.aws/aws-containers/retail-store-sample-cart:1.2.1"
  port: 8080
  env:
    RETAIL_CART_PERSISTENCE_PROVIDER: "in-memory"
    RETAIL_CART_PERSISTENCE_DYNAMODB_TABLE_NAME: "Items"
    RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE: "false"

  service:
    enabled: true
